#!/usr/bin/python

import random
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)

buzz_pin = 32
led_pin = 11

GPIO.setup(buzz_pin, GPIO.OUT)
GPIO.setup(led_pin, GPIO.OUT)

Buzz = GPIO.PWM(buzz_pin, 1000)

rand = random.randint(0,10)
guess = int(input("Enter an integer: "))
if guess == rand: 
    GPIO.output(led_pin, True)
    time.sleep(2)
else:
    Buzz.ChangeFrequency(3000)
    Buzz.start(10)
    time.sleep(50)
    
GPIO.output(led_pin, False)
GPIO.output(buzz_pin, False)

GPIO.cleanup()


    
    
    
    